// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Provide a valid format fallback for build time static analysis
const dbUrl = process.env["DATABASE_URL"] || "postgresql://johndoe:randompassword@localhost:5432/mydb?schema=public";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: dbUrl,
  },
});
